# -*- coding: utf-8 -*-
"""Despliegue-Videojuegoscontreamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qRgu-x52GDbQgEc0WB6Qu3RzEa_DB6ZB

##despliegue
- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros: normalizar, dummies
- Aplicamos el modelo para la predicción
"""

#Cargamos librerías principales

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#cargar el modelo
#Cargamos el modelo
import pickle
filename = 'modelo-reg.pkl'
modelo, min_max_scaler, variables = pickle.load(open(filename, 'rb'))

modelo

#cargar datos futuros
#Cargamos los datos futuros
#data = pd.read_csv("videojuegos-datosFuturos.csv")
#data.head()

#interfaz grafica de streamlit


#Se crea interfaz gráfica con streamlit para captura de los datos



import streamlit as st

st.title('Predicción de inversión en una tienda de videojuegos')


Edad = st.slider('Edad', min_value=14, max_value=52, value=20, step=1)
videojuego = st.selectbox('Videojuego', ["'Mass Effect'","'Battlefield'", "'Fifa'","'KOA: Reckoning'","'Crysis'","'Sim City'","'Dead Space'","'F1'"])
Plataforma = st.selectbox('Plataforma', ["'Play Station'", "'Xbox'","PC","Otros"])
Sexo = st.selectbox('Sexo', ['Hombre', 'Mujer'])
Consumidor_habitual = st.selectbox('Consumidor_habitual', ['True', 'False'])

#Dataframe

datos = [[Edad, videojuego,Plataforma,Sexo,Consumidor_habitual]]

data = pd.DataFrame(datos, columns=['Edad', 'videojuego','Plataforma','Sexo','Consumidor_habitual']) #Dataframe con los mismos nombres de variables

#preparación de los datos
#primero hago una copia de los datos
#Se realiza la preparación de datos
data_preparada=data.copy()

#En despliegue drop_first= False
data_preparada = pd.get_dummies(data_preparada, columns=['videojuego', 'Plataforma','Sexo', 'Consumidor_habitual'], drop_first=False, dtype=int)
data_preparada.head()

Y_pred = modelo.predict(data_preparada)

#Se adicionan las columnas faltantes
data_preparada=data_preparada.reindex(columns=variables,fill_value=0)
data_preparada.head()

##knn,svr,red
#Se normaliza la edad para predecir con Knn, Red, SVM, Reg
#En los despliegues no se llama fit
#data_preparada[['Edad']]= min_max_scaler.transform(data_preparada[['Edad']])
#data_preparada.head()

"""# ***PREDICCIONES***"""

#Hacemos la predicción con el Tree
Y_pred = modelo.predict(data_preparada)
print(Y_pred)

data['Prediccion <3']=Y_pred
data.head()

#preducciones finales
data

#avertencia con streamlit
# Recordar medida de error del modelo

st.warning("El modelo tiene un error del 	0.000831% (mape: error porcentual)")